__all__ = [
    "BAD_REQUEST_ERROR_CODE",
    "CONFLICT_ERROR_CODE",
    "DRF_ERROR_CODE_MAP",
    "FORBIDDEN_ERROR_CODE",
    "INTERNAL_ERROR_CODE",
    "NOT_FOUND_ERROR_CODE",
    "UNAUTHORIZED_ERROR_CODE",
    "VALIDATION_ERROR_CODE",
]

INTERNAL_ERROR_CODE = "INTERNAL_ERROR"
VALIDATION_ERROR_CODE = "VALIDATION_ERROR"
UNAUTHORIZED_ERROR_CODE = "UNAUTHORIZED"
FORBIDDEN_ERROR_CODE = "FORBIDDEN"
NOT_FOUND_ERROR_CODE = "NOT_FOUND"
BAD_REQUEST_ERROR_CODE = "BAD_REQUEST"
CONFLICT_ERROR_CODE = "CONFLICT"

DRF_ERROR_CODE_MAP: dict[str, str] = {
    "authentication_failed": UNAUTHORIZED_ERROR_CODE,
    "invalid": VALIDATION_ERROR_CODE,
    "method_not_allowed": "METHOD_NOT_ALLOWED",
    "not_acceptable": "NOT_ACCEPTABLE",
    "not_authenticated": UNAUTHORIZED_ERROR_CODE,
    "not_found": NOT_FOUND_ERROR_CODE,
    "parse_error": BAD_REQUEST_ERROR_CODE,
    "permission_denied": FORBIDDEN_ERROR_CODE,
    "throttled": "THROTTLED",
    "unsupported_media_type": "UNSUPPORTED_MEDIA_TYPE",
}
