# Generated by Django 6.0.6 on 2026-06-09 01:33

import zoneinfo

import django_countries.fields
import phonenumber_field.modelfields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the user.",
                        max_length=128,
                        verbose_name="name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={"unique": "A user with that email already exists."},
                        help_text="The email address of the user.",
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user's email is verified.",
                        verbose_name="email verified",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        error_messages={
                            "unique": "A user with that phone number already exists."
                        },
                        help_text="The phone number of the user.",
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "phone_number_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user's phone number is verified.",
                        verbose_name="phone number verified",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="The avatar of the user.",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="The country of the user.",
                        max_length=2,
                        null=True,
                        verbose_name="country",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="The locale of the user.",
                        max_length=128,
                        verbose_name="locale",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        choices_display="WITH_GMT_OFFSET",
                        default=zoneinfo.ZoneInfo(key="UTC"),
                        help_text="The timezone of the user.",
                        verbose_name="timezone",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is banned.",
                        verbose_name="banned",
                    ),
                ),
                (
                    "banned_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The reason the user was banned.",
                        verbose_name="banned reason",
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the user was banned.",
                        null=True,
                        verbose_name="banned at",
                    ),
                ),
                (
                    "banned_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the user will be unbanned.",
                        null=True,
                        verbose_name="banned until",
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has two factor authentication enabled.",
                        verbose_name="two factor enabled",
                    ),
                ),
                (
                    "last_login_method",
                    models.CharField(
                        choices=[
                            ("credentials", "Credentials"),
                            ("magic_link", "Magic Link"),
                            ("google", "Google"),
                            ("apple", "Apple"),
                        ],
                        default="credentials",
                        editable=False,
                        help_text="The method the user last logged in with.",
                        max_length=128,
                        verbose_name="last login method",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="The date and time the user last logged in.",
                        null=True,
                        verbose_name="last login",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        editable=False,
                        help_text="The IP address the user last logged in from.",
                        null=True,
                        verbose_name="last login ip",
                    ),
                ),
                (
                    "last_logout",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="The date and time the user last logged out.",
                        null=True,
                        verbose_name="last logout at",
                    ),
                ),
                (
                    "last_logout_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        editable=False,
                        help_text="The IP address the user last logged out from.",
                        null=True,
                        verbose_name="last logout ip",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time the user was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the user joined the platform.",
                        verbose_name="date joined",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "ordering": ("-date_joined", "-id"),
            },
        ),
    ]
